# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
