# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20170111_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='starring',
            field=models.ManyToManyField(blank=True, through='homework.Role', to='homework.Person'),
        ),
    ]
