# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='tool',
            field=models.ManyToManyField(blank=True, to='exercises.Tool'),
        ),
    ]
