# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20170111_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizze'},
        ),
        migrations.AddField(
            model_name='pizza',
            name='sent_to_customer',
            field=models.BooleanField(default=False, verbose_name='Wysłana do klienta?'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.IntegerField(choices=[(1, 'small'), (2, 'medium'), (3, 'big')], verbose_name='rozmiar'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='exercises.Topping', verbose_name='dodatki'),
        ),
    ]
